name: coq2bpl
version: 0.1.0
synopsis: A codegen from Coq extracted JSON to C++17
description: Based on Mach7, soon in C++17
maintainer: Eleftherios Ioannidis <elefthei@mit.edu>
license: MIT
github: elefthei/coq2bpl
category: Development

ghc-options: -Wntabs

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - deepseq
  - directory
  - aeson
  - filepath
  - ansi-wl-pprint
  - containers
  - html
  - lens
  - transformers
  - mtl
  - logict
  - parsec
  - random
  - stream-monad
  - syb
  - z3
  - text
  - aeson
  - stringsearch

executable:
  main: Main.hs
  source-dirs:
    - lib
    - src

tests:
  spec:
    cpp-options: -DTEST
    main: Json.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec

